import Head from 'next/head';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import { Card } from 'antd';

// assets
import styles from '../styles/header.module.css';


export default function Home() {
  const [isMounted, setIsMounted] = useState(false);
  const [characters, setCharacters] = useState([]);

  useEffect(() => {
    setIsMounted(true);

    fetch('https://gateway.marvel.com:443/v1/public/characters?apikey=a0047ef072eeea4d0c192bb4e3b39adf')
      .then(res => res.json())
      .then(resp => setCharacters(resp.data.results));
  }, []);

  console.log(process.env.REACT_APP_API_KEY);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>

      </header>
      <main>
        { isMounted && <h1>Hello World</h1> }
        <div className={styles.list}>
          {
            characters.map((character, index) => (
              <Card
                hoverable
                key={index}
                style={{ width: 240 }}
                cover={
                <img alt="example" src={`${character.thumbnail.path}/portrait_xlarge.jpg`} />
              }
              >
              <Card.Meta title={character.name} description={character.description} />
            </Card>
            ))
          }
        </div>
      </main>
      <Link href="/about-us">
        About Us
      </Link>
    </>
  )
}
